#
# ATTENTION: This file is automatically generated. do not try to edit it.
#

import struct
import logging


# noinspection PyClassHasNoInit
class AuthStatus():
    NONE, AUTH_SUCCESS, NAME_OCCUPIED, UNKNOWN = range(4)


# noinspection PyClassHasNoInit
class EnterWorldStatus():
    NONE, ENTER_SUCCESS, TOO_MANY_USERS, UNKNOWN = range(4)


